workflows:
  test_workflow:
    name: Run tests for one Dart file
    environment:
      flutter: stable # If you are using Dart only, you can remove the flutter section.
      # You can specify your preferred version of Dart if needed.
    scripts:
      - name: Run unit tests for one file
        script: |
          Desktop/SE2Phase3/NewSecCode.dart
