name: Dart Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.5.3'  # تأكد من استخدام النسخة الصحيحة

    - name: Install dependencies
      run: dart pub get

    - name: Run tests
      run: dart test
